export const Projects = [
    { title: 'StudPro', skills:["Méthode Agiles","Reactjs","Nextjs14","TypeScript","Docker","Prisma","PotgreSQL","NextAUTH"],  description: "Pendant mon stage chez StudPro , j'ai réussi à convertir avec succès les conceptions élaborées par les designers en interfaces utilisateur attrayantes en utilisant ReactJS et NextJS. J'ai également créé des APIs REST et mis en place une authentification complète en utilisant à la fois la vérification par e-mail et par SMS. J'ai contribué à l'expérience utilisateur en créant plusieurs pages et formulaires pour les comptes. De plus, j'ai résolu efficacement les problèmes de codage, assurant ainsi la stabilité et la fonctionnalité optimale des applications web.", image: '/images/studpro.png', url: '' },
    { title: 'Mon Salon Connect',skills:["Reactjs","Nextjs13",'TypeScript',"ReactQuery","NextAUTH","MongoDB","Stripe","Redux Toolkit","Cloudinary"], description: "Ce projet est un plateforme qui facilite la mise en relation entre les clients à la recherche de coiffeurs dans leur région. Les clients peuvent créer un compte sur le site pour prendre des rendez-vous avec les coiffeurs et réserver une coupe à une date et une heure spécifique. Les coiffeurs ont la possibilité de publier des images de leurs coupes, accompagnées de leurs prix, ainsi que de spécifier leurs horaires d'ouverture et de fermeture. Ils peuvent également confirmer ou annuler les rendez-vous pris par les clients. En résumé, ce site offre une solution pratique pour les clients qui cherchent des coiffeurs et pour les coiffeurs qui souhaitent promouvoir leurs services et gérer leurs rendez-vous en ligne.", image: '/images/monsalonconnect.png', url: 'https://monsalonconnect.com' },
    { title: 'My Cyber Shop', skills:["Reactjs","Nextjs13",'TypeScript',"ReactQuery","NextAUTH","MongoDB","Stripe","Redux Toolkit","Cloudinary"], description: "Ce projet est un plateforme en ligne qui propose une large gamme d'électroménagers, de meubles et de packs informatiques. Les utilisateurs peuvent créer un compte sur le site pour accéder à différentes fonctionnalités telles que la gestion de leur panier d'achats, la sauvegarde de leurs informations personnelles et l'historique de leurs commandes. Le site permet également aux utilisateurs de faire des paiements en ligne de manière sécurisée, en utilisant divers modes de paiement tels que les cartes de crédit, les virements bancaires ou les portefeuilles électroniques. Les produits sont présentés avec des descriptions détaillées, des images et des avis des clients, ce qui aide les utilisateurs à prendre des décisions éclairées. Grâce à cette plateforme, les utilisateurs peuvent facilement parcourir les différentes catégories de produits, comparer les prix et les caractéristiques, et passer des commandes en toute simplicité depuis le confort de leur domicile. Le site ecommerce offre une expérience pratique et sécurisée pour les achats en ligne d'électroménagers, de meubles et de packs informatiques.", image: '/images/mycybershop.png', url: 'https://mycybershop.store' },
    { title: 'Emmtaboutique', skills:["Reactjs","Nextjs13",'TypeScript',"ReactQuery","NextAUTH","MongoDB","Stripe","Redux Toolkit","Cloudinary"] , description: "Bénévolat  : Développer et entretenir un site web e-commerce pour une association qui se spécialise dans la vente de produits d'occasion. Ce site permet aux utilisateurs d'explorer une variété de produits d'occasion, tels que des vêtements, des meubles, des appareils électroniques, et bien plus encore. Les bénévoles travaillent sur le développement du site, en s'assurant qu'il propose une interface utilisateur conviviale et attrayante, permettant aux utilisateurs de naviguer facilement entre les différentes catégories de produits et de trouver ce qu'ils recherchent. Ils se chargent également de la maintenance du site, en veillant à ce que toutes les fonctionnalités soient opérationnelles et que les problèmes techniques soient résolus rapidement. L'association vise à offrir une expérience d'achat en ligne fluide et sécurisée, en mettant en place des solutions de paiement en ligne et en garantissant la confidentialité des informations personnelles des utilisateurs.", image: '/images/emmaus.png', url: 'https://emmtaboutique.com' },
    { title: 'Online Screen Recorder', skills:["Reactjs","Express",'TypeScript',"NextAUTH","MongoDB","Stripe"] , description: "Ce projet offre la fonctionnalité d'enregistrement d'écran pour le navigateur. Il permet aux utilisateurs d'enregistrer leurs sessions de navigation et de les sauvegarder dans une base de données ou de les télécharger. Cette fonction est utile à diverses fins, telles que la documentation des interactions sur les sites web, la création de tutoriels ou la capture d'informations importantes lors de recherches en ligne.En utilisant la fonction d'enregistrement d'écran, les utilisateurs peuvent capturer l'intégralité de leur expérience de navigation ou des zones spécifiques de l'écran. Cela peut être bénéfique pour démontrer des tâches spécifiques, présenter les fonctionnalités d'un site web ou résoudre des problèmes. Les sessions enregistrées peuvent être sauvegardées dans une base de données, ce qui permet aux utilisateurs d'y accéder et de les consulter ultérieurement. Alternativement, les utilisateurs peuvent choisir de télécharger les sessions enregistrées pour les visionner hors ligne ou les partager avec d'autres personnes.", image: '/images/screen.png', url: '' },
    { title: 'Driiiblle clone', skills:["Reactjs","Nextjs13",'TypeScript',"NextAUTH","Grafbase","GraphQL","Stripe"] , description: " This project is a clone of Dribbble, a popular platform for showcasing and discovering creative work. It uses the NEXT13 APP folder as the main codebase, along with GraphQL for API communication and Grafbase as the database. Authentication is implemented using NEXTAUTH.", image: '/images/friible.png', url: '' },
  ];
  export const certificates = [
    { title: 'React - The Complete Guide 2024 (incl. React Router & Redux)', date : "22-10-2022" , description: 'Dive in and learn React.js from scratch! Learn React, Hooks, Redux, React Router, Next.js, Best Practices and way more!', image: '/images/reactUdemy.png', url: 'https://www.udemy.com/course/react-the-complete-guide-incl-redux/' },
    { title: 'Python Django , The Practical Guide', date:"28-02-2023" ,description: 'Learn how to build web applications and websites with Python and the Django framework', image: '/images/djangoUdemy.png', url: 'https://www.udemy.com/course/python-django-the-practical-guide/' },
    { title: 'Docker & Kubernetes: The Practical Guide [2024 Edition]', date:"Loading ... 80%", description: 'Learn Docker, Docker Compose, Multi-Container Projects, Deployment and all about Kubernetes from the ground up!', image: '/images/dockerUdemy.png', url: 'https://www.udemy.com/course/docker-kubernetes-the-practical-guide/' },
    { title: 'JavaScript Algorithms and Data Structures Masterclass', date:"Loading ... 75%", description: 'The Missing Computer Science and Coding Interview Bootcamp', image: '/images/jsUdemy.png', url: 'https://www.udemy.com/course/js-algorithms-and-data-structures-masterclass/' },
    { title: 'CISCO CERTIFICATION CCNA 1 2 3', date:"01-02-2022", description: 'The Missing Computer Science and Coding Interview Bootcamp', image: '/images/ccna.png', url: 'https://www.udemy.com/course/js-algorithms-and-data-structures-masterclass/' },
  ];